from enum import Enum

class TokenEnum(Enum):
  ATE = 'até'
  ATR = '<-'
  DE = 'de'
  E = 'e'
  ENQUANTO = 'enquanto'
  ENTAO = 'então'
  ESCREVA = 'escreva'
  FACA = 'faça'
  FIMPARA = 'fim_para'
  FIMSE = 'fim_se'
  FIMENQUANTO = 'fimenquanto'
  ID = 'identifier'
  LEIA = 'leia'
  LOGDIFF = '<>'
  LOGIGUAL = '='
  LOGMAIOR = '>'
  LOGMAIORIGUAL = '>='
  LOGMENOR = '<'
  LOGMENORIGUAL = '<='
  NAO = 'não'
  NUMINT = 'integer value'
  OPDIVI = '/'
  OPMAIS = '+'
  OPMENOS = '-'
  OPMULTI = '*'
  OU = 'ou'
  PARA = 'para'
  PARAB = '('
  PARFE = ')'
  PASSO = 'passo'
  SE = 'se'
  SENAO = 'senão'
  STRING = 'string value'
  TIPO = 'inteiro'

  # Additional Tokens (not in documentation)
  ALGORITMO = 'algoritmo'
  VAR = 'var'
  COMMA = ','
  COLON = ':'
  INICIO = 'inicio'
  FIMALGORITMO = 'fimalgoritmo'
  END_OF_FILE = '__EOF__'
